import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Transaction, TransactionStatus } from './entities/transaction.entity';

@Injectable()
export class TransactionsRepository {
  constructor(
    @InjectRepository(Transaction)
    private readonly repo: Repository<Transaction>,
  ) {}

  create(tx: Partial<Transaction>) {
    return this.repo.create(tx);
  }

  save(tx: Transaction) {
    return this.repo.save(tx);
  }

  findById(churchId: string, id: string) {
    return this.repo.findOne({ where: { id, churchId } });
  }

  /**
   * For provider callbacks where tenant context is not available.
   * Only safe because transaction IDs are UUIDs generated by us.
   */
  findByIdGlobal(id: string) {
    return this.repo.findOne({ where: { id } });
  }

  findByIdempotencyKey(churchId: string, idempotencyKey: string) {
    return this.repo.findOne({ where: { churchId, idempotencyKey } });
  }

  listByUser(churchId: string, userId: string, limit = 50) {
    return this.repo.find({
      where: { churchId, userId },
      order: { createdAt: 'DESC' },
      take: Math.min(limit, 200),
    });
  }

  listByChurch(churchId: string, limit = 50) {
    return this.repo.find({
      where: { churchId },
      order: { createdAt: 'DESC' },
      take: Math.min(limit, 200),
    });
  }

  async markSuccessful(churchId: string, id: string, momoReference?: string) {
    await this.repo.update(
      { id, churchId },
      { status: TransactionStatus.SUCCESSFUL, momoReference, failureReason: null },
    );
  }

  async markFailed(churchId: string, id: string, failureReason: string) {
    await this.repo.update({ id, churchId }, { status: TransactionStatus.FAILED, failureReason });
  }

  countByStatus(churchId: string, status: TransactionStatus) {
    return this.repo.count({ where: { churchId, status } });
  }

  async sumSuccessfulSince(churchId: string, start: Date) {
    const row = await this.repo
      .createQueryBuilder('t')
      .select('COALESCE(SUM(t.amount), 0)', 'sum')
      .where('t.church_id = :churchId', { churchId })
      .andWhere('t.status = :status', { status: TransactionStatus.SUCCESSFUL })
      .andWhere('t.created_at >= :start', { start })
      .getRawOne<{ sum: string }>();
    return Number(row?.sum ?? 0);
  }
}

